name: Docker Image CI (ghcr)

on:
  push:
    branches: [ "microai" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: microAI
    steps:
    - name: Call webhook on start
      run: |
        curl "https://microai.jp/api/webhook/line/simple-url-extractor%20actions%20start" --fail || true

    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: ghcr Auth
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
        push: true
        platforms: linux/amd64,linux/arm64

    - name: Call webhook on success
      if: success()
      run: |
        curl "https://microai.jp/api/webhook/line/simple-url-extractor%20actions%20success" --fail || true

    - name: Call webhook on failure
      if: failure()
      run: |
        curl "https://microai.jp/api/webhook/line/simple-url-extractor%20actions%20failure" --fail || true
